BEGIN; 

CREATE TABLE "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "firstname" text NULL,
  "lastname" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

ALTER TABLE "user" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'member';

COMMIT; -- Pour mettre fin à au bloc de transaction et l'exécuter